spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: L
      secret-key: o
      oss:
        endpoint: oss-cn-beijing.com
        bucket: g
      sms:
        host: c
        path: /yzx/sendSms
        tpl_id: T
        appcode: 7
  application:
    name: gulimall-third-party
server:
  port: 30000
