spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GFAafmwwXs1x382tmRW
      secret-key: oppmHsjY7A0rN9ma7HmMsOAX0rvS9W
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-lnj
  application:
    name: gulimall-third-party
server:
  port: 30000
